mysite/urls.py
#TODO: Learn extending django-profiles to add your own form elements---> http://dewful.com/?p=70


from django.conf.urls.defaults import *
#from basic.blog import views
#import satchmo_ext.productratings.models
from registration.backends.default.urls import *
from django.views.generic.simple import redirect_to
from django.contrib import admin
admin.autodiscover()

#from basic.books.models import *


urlpatterns = patterns('mysite.views',
    (r'^$', 'hello'),
    (r'^time/$', 'current_datetime'),
    (r'^time/plus/(\d{1,2})/$', 'hours_ahead'),
    (r'^meta/$', 'display_meta'),
    (r'^color/$', 'set_color'),
    (r'^accounts/profile',redirect_to, {'url': '/profiles/'} ),
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^accounts/', include('registration.backends.default.urls')),
    #(r'^accounts/',redirect_to, {'url': '/accounts/login'} ),
    (r'^profiles/', include('profiles.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)


urlpatterns += patterns('mysite.contact.views',
    (r'^contact/$', 'contactview'),
    (r'^contact/thankyou/$', 'thankyou'),
)


urlpatterns += patterns('mysite.books.views',
    (r'^search-form/$', 'search_form'),
    (r'^search/$', 'search'),
)

urlpatterns += patterns('mysite.colleges.views',
    (r'^search-page/$', 'search_page'),
    (r'^searchc/$', 'searchc'),
)


"""
from django.views.generic import DetailView, ListView
from mysite.polls.models import Poll

urlpatterns += patterns('mysite.polls.views',
    url(r'^polls/$',ListView.as_view(queryset=Poll.objects.order_by('-pub_date')[:5],context_object_name='latest_poll_list',template_name='polls/index.html')),
    url(r'^polls/(?P<pk>\d+)/$',DetailView.as_view(model=Poll,template_name='polls/detail.html')),
    url(r'^polls/(?P<pk>\d+)/results/$',DetailView.as_view(model=Poll,template_name='polls/results.html'),name='poll_results'),
    url(r'^polls/(?P<poll_id>\d+)/vote/$', 'polls.views.vote'),
)
"""

mysite/contact/models.py
########## models.py #############
from django import forms
from django.forms.widgets import *
from django.core.mail import send_mail, BadHeaderError

# A simple contact form with four fields.
class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    topic = forms.CharField()
    message = forms.CharField(widget=Textarea())

mysite/polls/models.py
from django.db import models

class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField()
    
    def __unicode__(self):
        return self.question
        

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice = models.CharField(max_length=200)
    votes = models.IntegerField()
    
    def __unicode__(self):
        return self.choice

# Create your models here.

mysite/contact/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False, label='Your e-mail address')
    message = forms.CharField(widget=forms.Textarea)
    
    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words!")
        return message

mysite/contact/views.py
########## views.py ##############
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from contact.models import ContactForm
from django.template import RequestContext, Context
from django import forms
from django.forms.widgets import *
from django.core.mail import send_mail, BadHeaderError

def contactview(request):
    subject = request.POST.get('topic', '')
    message = request.POST.get('message', '')
    from_email = request.POST.get('email', '')
    c = {'form':ContactForm()}
    if subject and message and from_email:
        try:
            send_mail(subject, message, from_email, ['admin@codesters.org'])
        except BadHeaderError:
            return HttpResponse('Invalid header found.')
        return HttpResponseRedirect('/contact/thankyou/')
    else:
        return render_to_response('contacts.html', {'form': ContactForm()})

    return render_to_response('contacts.html', c, context_instance=RequestContext(request))

def thankyou(request):
    return render_to_response('thankyou.html')

mysite/templates/base.html
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv = "X-UA-Compatible" content="IE=edge, chrome=1">
        <title>{% block title %}{% endblock %}</title>
        <meta name='description' content="{{ page_desc }}">
        <link rel="stylesheet" href="/static/style.css">
	 
   </head>
    <body>
        <div id="header">
        <h1> My Django Site </h1>
            <h2> {% block heading %}{% endblock %} </h2>

            <div id="nav">
                <ul>
                    <li><a href="{{ request.META.HTTP_HOST }}">Home</a></li>
                    <li><a href="/time ">Time</a></li>
                    <li><a href="/time/plus/2">Time Plus</a></li>
                    <li><a href="/admin">Admin Site</a></li>
                    <li><a href="/contact">Contact</a></li>
                    <li><a href="/meta">Your Info</a></li>
                    <li><a href="/search">Search</a></li>
                    <li><a href="/polls">Polls</a></li>
                    <li><a href="/blog">Blog</a></li>
                    <li><a href="/profiles/">Profile</a></li>
                    <li><a href="/accounts/logout">Logout</a></li>
                    <li><a href="{% url django.contrib.auth.views.login %}?next={{request.path}}">Login</a></li>
                </ul>
            </div>
        </div>
        <div id="content">
        {% block content %}{% endblock %}
        </div>
        {% block style %}
        <style>
        body {
	font-family:Arial;
	font-size:100%;
	text-decoration:none;
}

#header {
	margin: 20px;
	padding-bottom: 20px;
}

#header ul {	
	color:red;
}

a, a:visited {
    color:red;
    padding:0;
	text-decoration:none;
    margin:0;
}

#nav a,#nav a:visited {
	font-size:1.4em;
}

a:hover {
	color:#ff2222;
}

#header ul {
	list-style:none;
	display:inline;
}

#header ul li {
	display: inline;
	padding:10px 10px;
	border: double black 1px;
}
#content {
	padding:10px 10px;
	border: black 1px;
}
        </style>
{% endblock style %}
    </body>
</html>

mysite/templates/contacts.html
{% include 'header.html' %}

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">{% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
    
    
    <style type="text/css">
    ul.errorlist {
        margin: 0;
        padding: 0;
    }
    .errorlist li {
        background-color: red;
        color: white;
        display: block;
        font-size: 10px;
        margin: 0 0 3px;
        padding: 4px 5px;
    }
</style>

</body>
</html>

mysite/templates/current_datetime.html
{% include 'header.html' %}

        <p>It is now {{ current_date }}.</p>
    </body>
</html>

mysite/templates/header.html
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv = "X-UA-Compatible" content="IE=edge, chrome=1">
        <title>{{ page_title }}</title>
        <meta name='description' content="{{ page_desc }}">
        <link rel="stylesheet" href="/static/style.css">
	 
   </head>
    <body>
        <div id="header">
        <h1> My Django Site </h1>
            <h2>{{ page_heading}} </h2>

            <div id="nav">
                <ul>
                    <li><a href="">Home</a></li>
                    <li><a href="/time ">Time</a></li>
                    <li><a href="/time/plus/2">Time Plus</a></li>
                    <li><a href="/admin">Admin Site</a></li>
                    <li><a href="/contact">Contact</a></li>
                    <li><a href="/meta">Your Info</a></li>
                    <li><a href="/search">Search</a></li>
                    <li><a href="/polls">Polls</a></li>
                    <li><a href="/blog">Blog</a></li>
                    <li><a href="/profiles/">Profile</a></li>
                    <li><a href="/accounts/logout">Logout</a></li>
                    <li><a href="{% url django.contrib.auth.views.login %}?next={{request.path}}">Login</a></li>
                </ul>
            </div>
        </div>
            

mysite/templates/home.html
{% include 'header.html' %}

        <p>You are at {{ your_host }}{{ your_path }}</p>
        <p>Your user agent is {{ your_agent }} </p>
    </body>
</html>

mysite/templates/poll_index.html
{% include 'header.html' %}

<div id="poll">
    <ul>
        {% for poll in poll_list %}
        <li>{{ poll.question }}</br></br></li>
        {% endfor %}
    </ul>

</div>
</body>
</html>

mysite/templates/search_form.html
{% include 'header.html' %}

{% if errors %}
    <ul style="color: red; type: none;">
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
{% endif %}

    <form action="" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
</body>
</html>

mysite/templates/search_page.html
{% include 'header.html' %}

{% if errors %}
    <ul style="color: red; type: none;">
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
{% endif %}

    <form action="" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
</body>
</html>

mysite/templates/search_results.html
{% include 'header.html' %}

<p>You searched for: <strong>{{ query }}</strong></p>

{% if books %}
    <p>Found {{ books|length }} book{{ books|pluralize }}.</p>
    <ul>
        {% for book in books %}
        <li><b>Title: </b>{{ book.title }}</li>
        <li><b>Publisher: </b>{{ book.publisher}}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No books matched your search criteria.</p>
{% endif %}

</body>
</html>

mysite/templates/searchc_results.html
{% include 'header.html' %}

<p>You searched for: <strong>{{ query }}</strong></p>

{% if books %}
    <p>Found {{ colleges|length }} college{{ colleges|pluralize }}.</p>
    <ul>
        {% for college in colleges %}
        <li>{{ college.name }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No college matched your search criteria.</p>
{% endif %}

</body>
</html>

mysite/templates/serach_page.html
{% include 'header.html' %}

{% if errors %}
    <ul style="color: red; type: none;">
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
{% endif %}

    <form action="" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
</body>
</html>

mysite/templates/thankyou.html
{% include 'header.html' %}

mysite/templates/time_ahead.html
{% include 'header.html' %}

        <p>In {{ offset }} hour(s), it will be {{ dt }}.</p>
    </body>
</html>